version: '3.8'
services:
  rabbitmq:
    networks:
      - github-release-monitor
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
  postgres:
    container_name: "github-release-monitor-postgres"
    networks:
      - github-release-monitor
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: github-release-monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    command: postgres -c 'max_connections=500'
    volumes:
      - ./pg-data:/var/lib/postgresql/data
volumes:
  pg-data:

networks:
  github-release-monitor:
