version: '3.8'
services:
  backend:
    labels:
      shipyard.route: "/"
      shipyard.init: "make migrations"
      shipyard.liveness.http.path: "/ping"
      shipyard.liveness.http.initial_delay: 60
    build: "."
    depends_on:
      - postgres
    environment:
      ENVIRONMENT: "prod"
      GITHUB_TOKEN: ${GITHUB_TOKEN}
    ports:
      - "8080:8080"

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: github-release-monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    command: postgres -c 'max_connections=500'
    volumes:
      - ./pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    labels:
      shipyard.deploy.disk.size: 1Gi
